version: "3.8"
services:
  dev_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mgmt
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./init-db-dev.sql:/docker-entrypoint-initdb.d/init.sql