name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
#          - macos-clang

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc
#          - toolchain: macos-clang
#            os: macOS-latest
#            compiler: clang

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Docker Compose
      run: docker-compose -f docker-compose-dev.yml up -d

    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build --config ${{ matrix.configuration }}

    - name: Test
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        DB_HOST: dev_db
        DB_PORT: 5432
        DB_USER: root
        DB_PASS: root
        DB_NAME: mgmt
#      run: ctest -C ${{ matrix.configuration }}
      run: ./unit_tests
